import {
  darkerGrotesque,
  goldman,
  oswald,
  rajdhani,
  raleway,
  robotoCondensed,
  sulphurPoint,
} from "./fonts";
import "./globals.css";
import { classNames } from "./utils";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={classNames(
        "bg-gray-950 text-white",
        // robotoCondensed.className
        // darkerGrotesque.className
        // goldman.className
        // sulphurPoint.className
        // raleway.className
        // oswald.className
        rajdhani.className
      )}
    >
      <body className="overflow-x-hidden">{children}</body>
    </html>
  );
}
